apiVersion: v1
kind: Service
metadata:
  name: service-pod-a
spec:
  type: NodePort
  selector:
    app: first-pod
  ports:
    - port: 80
      targetPort: 80 # Its 80 because its nginx
      nodePort: 30000
